name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install
    - name: ESLint
      run: yarn lint:js
    - name: Types
      run: yarn lint:types

  tests_floating:
    name: Floating
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install --no-lockfile --non-interactive
    - name: Test
      run: yarn test

  tests_lts_releases:
    name: LTS & Releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
        - "ember-3.16-lts"
        - "ember-3.20-lts"
        - "ember-3.24-lts"
        - "ember-release"
        - "ember-beta"
        - "ember-canary"
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install
    - name: Test with ${{ matrix.scenario }}
      run: yarn test:try-one ${{ matrix.scenario }}

  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [tests]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

